<a href="https://colab.research.google.com/github/merucode/RL/blob/93-Project-Trader-Custom_enviromnet/01_Creating_a_Gym_Environment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone -b 93-Project-Trader-Custom_enviromnet https://github.com/merucode/RL.git
!cd RL && mv * ../

Cloning into 'RL'...
remote: Enumerating objects: 149, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 149 (delta 26), reused 0 (delta 0), pack-reused 80
Receiving objects: 100% (149/149), 8.65 MiB | 5.33 MiB/s, done.
Resolving deltas: 100% (53/53), done.


In [3]:
!pip install -e gym-examples

Obtaining file:///content/gym-examples
  Preparing metadata (setup.py) ... done
  Attempting uninstall: gym-examples
    Found existing installation: gym-examples 0.0.1
    Uninstalling gym-examples-0.0.1:
      Successfully uninstalled gym-examples-0.0.1
  Running setup.py develop for gym-examples


### NOTE: After inistall gym-examples, Restart runtime

In [1]:
import time
import matplotlib.pyplot as plt
import gym
import numpy as np

In [2]:
envs = gym.vector.make("gym_examples:TradeWorld-v0", num_envs=2)
envs.reset()
actions = np.array([0, 0])
envs.step(actions)

(OrderedDict([('agent',
               array([[4, 0],
                      [4, 3]])),
              ('target',
               array([[4, 4],
                      [2, 2]]))]),
 array([0, 0]),
 array([False, False]),
 array([False, False]),
 {'distance': array([4., 3.]), '_distance': array([ True,  True])})